name: C++ Build and Test

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up the C++ environment
    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang

    # Step 3: Compile the C++ project
    - name: Compile C++ project
      run: |
        #clang++ -o मुख्य_कार्यक्रम मुख्य_कार्यक्रम.cpp
        clang++  main.cpp -o main
        #clang++ -o हिंदी हिंदी.cpp

    # Step 4: Run the compiled program
    - name: Run the C++ program
      run: |
        ./main
        #./मुख्य_कार्यक्रम

    # Step 5: Optionally, add more steps for testing (if you have tests)
    # You can run your test cases or add additional checks here
    
